name: Dev
values:
  - key: JWT_TOKEN
    value: 'Error:getaddrinfo ENOTFOUND {{base_url}}'
  - key: BASE_URL
    value: ''
  - key: owner
    value: ''
  - key: repo
    value: ''
  - key: pull_number
    value: ''
  - key: queue_name
    value: ''
